{% set name = "bps-stack_cal_processor" %}
{% set version = "4.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file://{{ RECIPE_DIR }}/../dist/bps_stack_cal_processor-{{ version }}.tar.gz

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.12
    - numpy
    - arepytools >=1.7.6
    - bps-common =={{ version }}
    - numba >=0.57.0
    - py-opencv=*=*headless*
    - scipy
    - scikit-image
    - scikit-learn

test:
  imports:
    - bps
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Biomass Stack Calibration Processor package.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Aresys srl
