{% set name = "bps-stack_processor" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file://{{ RECIPE_DIR }}/../dist/bps_stack_processor-{{ version }}.tar.gz

build:
  entry_points:
    - bps_stack_processor = bps.stack_processor.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python }}
    - setuptools
    - wheel
    - pip
  run:
    - python {{ python }}
    - numpy
    - arepytools >=1.7.6
    - click
    - xsdata
    - xmltodict
    - arepyextras-runner
    - bps-common =={{ version }}
    - bps-stack_pre_processor =={{ version }}
    - bps-stack_coreg_processor =={{ version }}
    - bps-stack_cal_processor =={{ version }}
    - bps-transcoder =={{ version }}

test:
  imports:
    - bps
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Biomass Stack Processor.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Aresys srl
