{% set name = "bps-l1_framing_processor" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file://{{ RECIPE_DIR }}/../dist/bps_l1_framing_processor-{{ version }}.tar.gz

build:
  entry_points:
    - bps_l1_framing_processor = bps.l1_framing_processor.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python }}
    - setuptools
    - wheel
    - pip
  run:
    - _openmp_mutex
    - libgcc-ng
    - python {{ python }}
    - numpy
    - arepytools
    - click
    - xsdata
    - scipy
    - bps-common =={{ version }}
    - bps-transcoder =={{ version }}

test:
  imports:
    - bps
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Biomass L1 Framing Processor.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Aresys srl
