# Project: BIOMASS Processing Suite (BPS)
#
# Copyright (c) 2025, ARESYS S.r.l.
# Developed under contract with the European Space Agency (ESA)
#
# SPDX-License-Identifier: MIT

"""
Constants module
"""

import numpy as np

# Overall constants
SECONDS_PER_DAY = 60.0 * 60.0 * 24.0  # [s]

# BIOMASS-specific constants
ORBITAL_PERIOD = 5890.98007989  # [s]
REFERENCE_EPOCH = np.datetime64("2000-01-01T00:00:00")

# BIOMASS slicing and framing constants
NUMBER_OF_FRAMES_PER_ORBIT = 310
FRAME_TIME_GRID_SPACING = ORBITAL_PERIOD / NUMBER_OF_FRAMES_PER_ORBIT  # [s]
FRAME_ANGLE_GRID_SPACING = 360 / NUMBER_OF_FRAMES_PER_ORBIT  # [deg]
FRAME_OVERLAP = 2  # [s]
NOMINAL_FRAME_LENGTH = FRAME_TIME_GRID_SPACING + FRAME_OVERLAP  # [s]
MINIMUM_FRAME_LENGTH = 8  # [s]
NUMBER_OF_FRAMES_PER_SLICE = 5
SLICE_OVERLAP_LEFT = 10  # [s]
SLICE_OVERLAP_RIGHT = 12  # [s]
SLICE_OVERLAP = SLICE_OVERLAP_LEFT + SLICE_OVERLAP_RIGHT  # [s]
NOMINAL_SLICE_LENGTH = FRAME_TIME_GRID_SPACING * NUMBER_OF_FRAMES_PER_SLICE + SLICE_OVERLAP  # [s]
MINIMUM_SLICE_LENGTH = 16  # [s]
NUMBER_OF_SLICES_PER_ORBIT = int(NUMBER_OF_FRAMES_PER_ORBIT / NUMBER_OF_FRAMES_PER_SLICE)
MINIMUM_DATATAKE_LENGTH = 28  # [s]
L1_PROCESSING_MARGIN = 2  # [s]

# Other useful constants
L0_SENSING_TIME_MARGIN = 2  # [s]
L0_THEORETICAL_TIME_MARGIN = 10  # [ms]
NOMINAL_FRAME_LENGTH_MARGIN = 0.1  # [s]
