# Project: BIOMASS Processing Suite (BPS)
#
# Copyright (c) 2025, ARESYS S.r.l.
# Developed under contract with the European Space Agency (ESA)
#
# SPDX-License-Identifier: MIT

"""
Intermediate Products Settings and Utilities
--------------------------------------------
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from shutil import rmtree

from arepytools.io.productfolder2 import is_product_folder

# Prefix for stack intermediate products subfolder.
STA_PRODUCTS_PREFIX = "STA_P_"

# Suffix for all product folders.
EXTRACTED_PF_SUFFIX = "_PF"

# Suffixes for all geometrical products.
GEO_ECEF_GRID_SUFFIX = "_XYZ"
GEO_LOOK_ANGLE_SUFFIX = "_Look"
GEO_INCIDENCE_ANGLE_SUFFIX = "_Inc"
GEO_SLOPE_ANGLE_SUFFIX = "_Slope"

# Suffixes for all coregistration products.
COR_COR_SUFFIX = "_Cor"
COR_DIST_SUFFIX = "_DAPD"
COR_QUALITY_SHIFT_SUFFIX = "_CSA"
COR_SHIFT_AZ_SUFFIX = "_CorAz"
COR_GEO_SHIFT_AZ_SUFFIX = "_CorAzGeo"
COR_SHIFT_RG_SUFFIX = "_CorRg"
COR_GEO_SHIFT_RG_SUFFIX = "_CorRgGeo"
COR_SYNTH_SUFFIX = "_DSI"
COR_VERTICAL_WAVENUMBER_SUFFIX = "_Kz"

# Suffix for the debug symbols. For advanced usage only.
COR_DEBUG_SUFFIX = "_DBG"

# The filename of the actualized coregistration path.
ACTUALIZED_COREGISTRATION_PATH = "actualizedCoregistrationParameters.xml"

# Suffixes for al the stack-cal cache.
CAL_CACHE_IONO_PHASE_SCREEN_SUFFIX = "_IonoL1PhaseScreen"
CAL_CACHE_IONO_RANGE_SHIFTS_SUFFIX = "_IonoL1RangeShifts"

# Breakpoints and default directory.
INTERMEDIATE_FOLDER_TAG = "IntermediateDataDir"
INTERMEDIATE_FOLDER = "intermediate_dir"

# Default breakpoint directory for the pre-processor.
STACK_PRE_PROC_INTERMEDIATE_FOLDER = "stack_pre_processor_brk"

# Default breakpoint directory for the coreg-processor.
STACK_COREG_PROC_INTERMEDIATE_FOLDER = "stack_coreg_processor_brk"

# Default breakpoint directory for the cal-processor.
STACK_CAL_PROC_INTERMEDIATE_FOLDER = "stack_cal_processor_brk"


@dataclass
class StackPreProcessorOutputProducts:
    """Intermediate products generated by the Stack pre-processor."""

    raw_data_product: Path
    """Path tot the raw data product folder (i.e. before coregistration)."""

    xyz_product: Path
    """Path to the XYZ/ECEF coordinates before coregistration."""

    @classmethod
    def from_intermediate_dir(
        cls,
        intermediate_dir: Path,
        product_name: str,
        index: int,
    ) -> StackPreProcessorOutputProducts:
        """
        Setup the paths of the extracted products.

        Parameters
        ----------
        intermediate_dir: Path
            Intermediate directory where to save the intermediate products.

        product_name: str
            The L1a product name.

        index: int
            The index of the L1a product.

        Return
        ------
        StackPreProcessorOutputProducts
            Struct with the default paths to the products.

        """
        return cls(
            raw_data_product=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                f"{product_name}{EXTRACTED_PF_SUFFIX}",
            ),
            xyz_product=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                f"{product_name}{EXTRACTED_PF_SUFFIX}{GEO_ECEF_GRID_SUFFIX}",
            ),
        )

    def mkdir(self, **kwargs):
        """Create parent directories."""
        self.raw_data_product.parent.mkdir(**kwargs)

    def rmtree(self, **kwargs):
        """Remove the intermediate products."""
        for path in self.__dict__.values():
            rmtree(path, **kwargs)

    def are_product_folders(self, *, products: Iterable[str] | None = None) -> bool:
        """Check whether all paths are product folders."""
        if products is None:
            products = self.__dict__.keys()
        return all(is_product_folder(self.__dict__[prod]) for prod in products)


@dataclass
class CoregistrationOutputProducts:
    """Intermediate products of Coregistration Processor."""

    coreg_product: Path
    """The coregistered SLC."""

    actualized_coregistration_parameters_file: Path
    """The actual coregistered parameters XML file. It does not always exist."""

    synth_product: Path
    """The synthetic phases from DEM (DSI) [rad]."""

    kz_product: Path
    """The vertical wavenumbers (Kz) [rad]."""

    az_shifts_product: Path
    """The azimuth coregistration shifts [samples]."""

    az_geo_shifts_product: Path
    """The azimuth coregistration shifts using geometry [samples]."""

    rg_shifts_product: Path
    """The range coregistration shifts [samples]."""

    rg_geo_shifts_product: Path
    """The range coregistration shifts using geometry [samples]."""

    quality_shifts_product: Path
    """The coregistation shift quality [adim]."""

    distance_product: Path
    """Distance of the secondary trajectory to the primary xyz-image."""

    debug_product: Path
    """The debug products (for advanced usage only)."""

    l1_iono_phase_screen_product: Path
    """The product containing the phase screen from L1 [rad]."""

    l1_iono_range_shifts_product: Path
    """The product containing the iono range shifts from L1 [m]."""

    @classmethod
    def from_intermediate_dir(
        cls,
        intermediate_dir: Path,
        product_name: str,
        index: int,
    ) -> CoregistrationOutputProducts:
        """
        Setup the paths of the geometric intermediate products.

        Parameters
        ----------
        intermediate_dir: Path
            Intermediate directory where to save the intermediate products.

        product_name: str
            The product name.

        index: int
            The product index.

        Return
        ------
        CoregistrationOutputProducts
            Struct with the default paths to the products.

        """
        return cls(
            coreg_product=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                f"{product_name}{EXTRACTED_PF_SUFFIX}{COR_COR_SUFFIX}",
            ),
            actualized_coregistration_parameters_file=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                ACTUALIZED_COREGISTRATION_PATH,
            ),
            synth_product=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                f"{product_name}{EXTRACTED_PF_SUFFIX}{COR_SYNTH_SUFFIX}",
            ),
            kz_product=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                f"{product_name}{EXTRACTED_PF_SUFFIX}{COR_VERTICAL_WAVENUMBER_SUFFIX}",
            ),
            az_shifts_product=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                f"{product_name}{EXTRACTED_PF_SUFFIX}{COR_SHIFT_AZ_SUFFIX}",
            ),
            az_geo_shifts_product=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                f"{product_name}{EXTRACTED_PF_SUFFIX}{COR_GEO_SHIFT_AZ_SUFFIX}",
            ),
            rg_shifts_product=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                f"{product_name}{EXTRACTED_PF_SUFFIX}{COR_SHIFT_RG_SUFFIX}",
            ),
            rg_geo_shifts_product=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                f"{product_name}{EXTRACTED_PF_SUFFIX}{COR_GEO_SHIFT_RG_SUFFIX}",
            ),
            quality_shifts_product=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                f"{product_name}{EXTRACTED_PF_SUFFIX}{COR_QUALITY_SHIFT_SUFFIX}",
            ),
            distance_product=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                f"{product_name}{EXTRACTED_PF_SUFFIX}{COR_DIST_SUFFIX}",
            ),
            debug_product=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                f"{product_name}{EXTRACTED_PF_SUFFIX}{COR_DEBUG_SUFFIX}",
            ),
            l1_iono_phase_screen_product=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                f"{product_name}{EXTRACTED_PF_SUFFIX}{CAL_CACHE_IONO_PHASE_SCREEN_SUFFIX}",
            ),
            l1_iono_range_shifts_product=intermediate_dir.joinpath(
                f"{STA_PRODUCTS_PREFIX}{index + 1:0>2d}",
                f"{product_name}{EXTRACTED_PF_SUFFIX}{CAL_CACHE_IONO_RANGE_SHIFTS_SUFFIX}",
            ),
        )

    def mkdir(self, **kwargs):
        """Create parent directories."""
        self.coreg_product.parent.mkdir(**kwargs)

    def rmtree(self, **kwargs):
        """Remove the output products."""
        rmtree(self.coreg_product.parent, **kwargs)

    def are_product_folders(self, *, products: Iterable[str] | None = None) -> bool:
        """Check whether all paths are product folders."""
        if products is None:
            products = self.__dict__.keys()
        return all(is_product_folder(self.__dict__[prod]) for prod in products)
