<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.1">
	<xs:include schemaLocation="../../common/v1_4/IF_PF_Proc_common.xsd"/>
	<xs:annotation>
		<xs:documentation>This schema defines the format of a Task Table, contains the definition of a processor, in terms of:
- Composing Tasks.
- List of inputs and outputs for each Task.
The Task Table is used by the Processing Facility to identify the Tasks to be executed together with possible inter-dependencies. It determines the associated Task executables, identifies processing requirements and specific configuration file(s), specifies input data to be provided and output data to be collected.
The Root element of the "Task Table" I/F is the Task_Table xml element.

2023/11/29: update to ICD 1.4 (Task.List_of_RAMDISKs, schemaLocation is optional) Checked 2024/03/13
</xs:documentation>
	</xs:annotation>
	<xs:element name="Task_Table" type="Task_Table_Type">
		<xs:annotation>
			<xs:documentation>Root element of the "Task Table" I/F XML document.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="Task_Table_Type">
		<xs:sequence>
			<xs:element ref="Processor_Name"/>
			<xs:element ref="Processor_Version"/>
			<xs:element name="Author" type="xs:string">
				<xs:annotation>
					<xs:documentation>Author of the file.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="List_of_Tasks">
				<xs:annotation>
					<xs:documentation>List of Task elements.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Task" type="TT_Task_Type" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>Specification of the processing Task.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="schemaName" type="xs:string"/>
		<xs:attribute name="schemaVersion" type="xs:string"/>
		<xs:attribute name="schemaLocation" type="xs:string" use="optional"/>
	</xs:complexType>
	<!--=====================================================================-->
	<xs:complexType name="Alternative_Type_Type">
		<xs:sequence>
			<xs:element ref="File_Type"/>
			<xs:element name="Origin" type="xs:string">
				<xs:annotation>
					<xs:documentation>Specifies where the PF has to select the input data from. Possible values are:
•	“EXTERNAL”: the input has to be selected from the inventory before starting the processor (i.e. this input is not generated by the processor itself).
•	Task_Name/Task_Version: the input is selected among the outputs of the specified task. In this case, a dependency is defined between the two tasks, and the one originating the input data has to be completed before this task can start.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Instances" type="xs:string">
				<xs:annotation>
					<xs:documentation>This field specifies how the task is executed when the input of this type is made of multiple files. This is especially used for handling the input from previous tasks which produce multiple output products. Possible values are:
•	“SINGLE”: A single instance of the Task is executed which is provided with all the available input products.
•	“MULTIPLE”: A different instance of the Task is executed for each single available input. For each task there must be a maximum of one input alternative type with the Instances field set to “MULTIPLE”</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Selection_Parameters" type="Selection_Parameters_Type">
				<xs:annotation>
					<xs:documentation>This field specifies the combination of temporal, geospatial and metadata parameters to be used to select the input data.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Max_Number_of_Files" type="xs:positiveInteger">
				<xs:annotation>
					<xs:documentation>Specifies how many files of each type are allowed to be selected and provided in input to the Task.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Max_Number_to_Plugin" type="xs:positiveInteger" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Specifies how many files of each type are allowed to be selected and provided in input to the plugin implementing the Filter Algorithm.
If this element is not present or it is empty, then all candidates files for the current file type, selected by the default selection criteria, are passed to the plugin.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Ordering" type="xs:string">
				<xs:annotation>
					<xs:documentation>Specifies the order of preference for the selection of input data. The matching files, for each file type, are ordered according to the specified criteria and then the first files are selected considering the value of Max_Number_of_Files field.
A comma separated list of ordering values can also be supported by the PF. In such a case, the ordering criteria in the list are applied one after the other (from left to right) in order of priority.
Possible values are:
•	MaxTemporalOverlap
•	MaxGeographicOverlap
•	Latest
•	ClosestStart
•	ClosestStop
•	BestTimeCentered
If an ordering criterion is not applicable in the current selection (e.g. ClosestStart in a Geospatial selection) the PF shall ignore it.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Virtual" type="YesNo_Type" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Flag to identify virtual input data. Possible values are:
•	“Yes”: the selected input is written into the Job Order but the corresponding file(s) are not actually made available to the processor in the working directory.
•	“No”: the input is written into the Job Order and corresponding files are made available to the processor in the working directory.
The flag is optional. If missing, the flag is assumed to be set to “No”.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Cores_Type">
		<xs:sequence>
			<xs:element name="Number" type="xs:decimal">
				<xs:annotation>
					<xs:documentation>Maximum number of cores that shall be used by the Task executable in order to meet the nominal performance requirement.

If the following Scalable parameter is set to “Yes”, the PF is allowed to increase or decrease this value applying a scaling factor and to specify in the Job Order the updated number of CPU cores that the Task is allowed to use. In such a case, the same scaling factor will be applied to all Tasks where the Scalable flag is set to “Yes”.

The Task executable shall ensure that during its execution the number of used cores will not exceed the value provided in the Job Order.

The value “0” means that the amount of used cores is negligible and that this task may share it with other Tasks of that kind.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Scalable">
				<xs:annotation>
					<xs:documentation>Scalability flag for the number of cores. Possible values are:
•	“Yes”: the PF shall apply a scaling factor to the number of cores defined by the Number parameter and the updated value shall be copied into the Job Order.
•	“No”: the scaling factor is not applied. The original value shall be assigned and is copied by the PF into the Job Order.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="YesNo_Type">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GPU_Type">
		<xs:sequence>
			<xs:element name="Type" type="xs:string">
				<xs:annotation>
					<xs:documentation>Tag identifying a specific type of processing node with the required GPU resources. The tag is used by the processing facility to select the proper processing node to run the processor. A list of possible processing node types should be defined.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Cores" type="Cores_Type">
				<xs:annotation>
					<xs:documentation>Specification of the required number of GPU cores.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="RAM" type="RAM_Type">
				<xs:annotation>
					<xs:documentation>Specification of the required amount of GPU RAM.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Mandatory" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>Defines if the presence of GPUs is mandatory for task execution or not. 
·	ιφ “true”: the task cannot be instanced without GPU cores.
·	if “false”: the task can be instanced even without GPU cores but performances could be highly impacted.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Exit_Code_Type">
		<xs:sequence>
			<xs:element name="Value" type="xs:nonNegativeInteger">
				<xs:annotation>
					<xs:documentation>Exit code value.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Description" type="xs:string">
				<xs:annotation>
					<xs:documentation>Description of the exit code.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Geospatial_Parameters_Type">
		<xs:sequence>
			<xs:element name="Geospatial_Offset" type="xs:float">
				<xs:annotation>
					<xs:documentation>Offset to be applied to the polygon identifying the processing request. It consists in a fixed value in kilometers to be applied at each edge of the polygon to expand/reduce it (positive/negative value).</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Overlap">
				<xs:annotation>
					<xs:documentation>Specifies if the footprint of the input data has to overlap the processing request area (modified by the Geospatial_Offset):
•	“Yes”: the footprint of the input data must overlap the processing request area. The following Min_Overlap element specifies the minimum overlap required to each single input file.
•	“No”: the footprint of the input data must not overlap the processing request area
•	“Both”: no constraint is specified on the overlap.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Both"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Min_Overlap">
				<xs:annotation>
					<xs:documentation>Number in the range [0, 100], which specifies the minimum percentage of overlap between the footprint of the input data and the processing request area.

The field is considered only if Overlap is set to “Yes” and it is ignored otherwise.

If Overlap is set to “Yes” and Min_Overlap is set to “0”, every percentage of overlap is considered acceptable.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="100"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Input_Alternative_Type">
		<xs:sequence>
			<xs:element ref="Alternative_ID"/>
			<xs:element name="List_of_Alternative_Types">
				<xs:annotation>
					<xs:documentation>List of Alternative_Type elements.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Alternative_Type" type="Alternative_Type_Type" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>This element defines one of the possible file types that have to be selected together, resulting in a combination of files defined by the alternative. For each alternative type the criteria used to select the input starting from the processing request are specified.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Filter_Algorithm" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Optional field univocally identifying a specific algorithm used by the PF to further filter the list of input data.

If the field is present, the PF shall apply the algorithm to possibly narrow down the preliminary list of input data files selected according to the selection criteria defined in the individual Alternative_Type elements. The filter algorithm will produce as output the list of filenames to be provided to the processor.

Any processing implementation compatible with this guideline shall implement at least the default selection criteria based on the combination of all fields as defined in the Alternative_Type table. The support for the Filter_Algorithm on the other hand is optional. In case a PF does not support this feature and is faced with a task table where such field is defined, that PF shall report an error and not start the associated processes as applying only the initial default part of an input selection filter may result into unexpected processor behaviour and outputs.

The Filter_Algorithm field is mainly anticipated for future use in case very specific selection criteria not supported by the default filters are required. Also, the way the filter shall be actually implemented (plug-ins, etc.) is expected to be implementation specific and out-of-scope of this guideline  . In any case, the following minimum list of parameters shall be provided by the PF to the Filter:
•	List of candidate files from first filtering stage 
•	Metadata as listed in metadata mapping file for each of the files in the above list
•	General information specifying in particular AOI, TOI and processing parameters specified in the job order file’s header.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TT_Input_Type">
		<xs:sequence>
			<xs:element ref="Input_ID"/>
			<xs:element name="Mandatory" type="YesNo_Type">
				<xs:annotation>
					<xs:documentation>Mandatory flag for the input data. Possible values are:
•	“Yes”: if this input is not available, the PF shall not trigger the corresponding Task.
•	“No”: The PF can trigger the Task without this input (may still degrade the quality of the output but deemed acceptable according to this flag).</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="List_of_Input_Alternatives">
				<xs:annotation>
					<xs:documentation>List of Input_Alternative elements.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Input_Alternative" type="Input_Alternative_Type" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>Defines one of the possible alternatives for the input data and specifies the criteria used to select the input starting from the processing request’s time window.

The Task Table shall list all the valid possible alternatives for a given input by order of priority .

For a given input, the actual alternative that will be provided to the processor by the PF will depend on several factors: processing context (e.g. some file type may not be available in NRT scenarios), alternative order (defining preferences) and actual file availability.

The alternatives define possible combination of files that are considered valid for the input. The first alternative that is satisfied, in the order of priority specified by the Task Table, is selected as input.

Each alternative can be a group of one or more file types, which are selected as a whole dataset in a coherent way. A selection is considered valid for a given alternative only if the selection of all specified file type within the alternative is successful. This is used to define as alternative not a single file but a coherent combination of files.

Each file type has its own selection criteria as defined by the alternative parameters.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TT_Intermediate_Output_Type">
		<xs:sequence>
			<xs:element ref="Intermediate_Output_ID"/>
			<xs:element name="Intermediate_Output_File" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Default intermediate output file name without leading path. If present, the PF shall copy it in the Job Order, otherwise, the PF shall define its own default value and copy it in the Job Order.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Intermediate_Output_Description" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Description of the intermediate output.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TT_Output_Type">
		<xs:sequence>
			<xs:element ref="File_Type"/>
			<xs:element ref="File_Name_Pattern"/>
			<xs:element name="Destination">
				<xs:annotation>
					<xs:documentation>Possible values are:
•	“Internal”: the output is used as an intermediate product to be used as input by other tasks. It is not collected by the PF at the end of the processing.
•	“External”: the output is collected by the PF at the end of the processing. This option does not preclude an internal use of this output by the processor itself.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Internal"/>
						<xs:enumeration value="External"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TT_Proc_Parameter_Type">
		<xs:sequence>
			<xs:element name="Name" type="xs:string">
				<xs:annotation>
					<xs:documentation>Name of the parameter.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Default_Value" type="xs:string">
				<xs:annotation>
					<xs:documentation>Default value assigned to the parameter. Depending on the implementation, this default value may be overwritten by the PF. A minimum implementation should at least ensure that the default values, specified in the Task Table, are copied into the Job Order file.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RAM_Type">
		<xs:sequence>
			<xs:element name="Amount" type="xs:positiveInteger">
				<xs:annotation>
					<xs:documentation>Maximum amount of RAM, in megabytes, that shall be used by the Task executable in order to meet the nominal performance require-ment.

If the following Scalable parameter is set to “Yes”, the PF is allowed to increase or decrease this value applying a scaling factor and to specify, in the Job Order, the updated maximum amount of RAM that the Task is allowed to use. In such a case, the same scaling factor will be applied to all Tasks where the Scalable flag is set to “Yes”.

The Task executable shall ensure that during its execution the used amount of RAM will not exceed the value provided in the Job Order.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Scalable">
				<xs:annotation>
					<xs:documentation>Scalability flag for the maximum amount of RAM. Possible values are:
•	“Yes”: the PF shall apply a scaling factor to the maximum amount of RAM defined by the Amount parameter and the updated value shall be copied into the Job Order (see Amount_of_RAM element).
•	“No”: the scaling factor is not applied. The original value is copied by the PF into the Job Order (see Amount_of_RAM element).</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="YesNo_Type">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Selection_Parameters_Type">
		<xs:sequence>
			<xs:element name="Temporal_Parameters" type="Temporal_Parameters_Type" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Temporal parameters for the input data selection.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Geospatial_Parameters" type="Geospatial_Parameters_Type" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Geospatial parameters for the input data selection.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="List_of_Metadata_Names" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Product metadata for the input data selection.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Metadata_Name" maxOccurs="unbounded" type="xs:string">
							<xs:annotation>
								<xs:documentation>Name of the product metadata to be used for the input data selection. This metadata name must be defined in the Product Metadata Mapping interface.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Temporal_Parameters_Type">
		<xs:sequence>
			<xs:element name="Start_Offset" type="xs:int">
				<xs:annotation>
					<xs:documentation>Offset in seconds to be applied to the start of the processing request time window before executing the input selection according to the rule specified by the following fields. By convention the value is subtracted from the start time (i.e. a positive value anticipates the start time).</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Stop_Offset" type="xs:int">
				<xs:annotation>
					<xs:documentation>Offset in seconds to be applied to the stop of the processing request time window before executing the input selection according to the rule specified by the following fields. By convention the value is added to
the stop time (i.e. a positive value delays the stop time).</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Overlap">
				<xs:annotation>
					<xs:documentation>Specifies if the time validity window of the input data has to overlap the processing request time window (modified by the above offsets):
•	“Yes”: the time validity of the input data must overlap the processing request time window. The following Min_Overlap element specifies the minimum overlap required to each single input file.
•	“No”: the time validity of the input data must not overlap the processing request time window
•	“Both”: no constraint is specified on the overlap.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Both"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Min_Overlap">
				<xs:annotation>
					<xs:documentation>Number in the range [0, 100], which specifies the minimum percentage of overlap between the time validity window of the input data and the time window of the processing request.

The field is considered only if Overlap is set to “Yes” and it is ignored otherwise.

If Overlap is set to “Yes” and Min_Overlap is set to “0”, every percentage of overlap is considered acceptable.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="100"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TT_Task_Type">
		<xs:sequence>
			<xs:element ref="Task_Name"/>
			<xs:element ref="Task_Version"/>
			<xs:element name="SW_Distribution" type="xs:string">
				<xs:annotation>
					<xs:documentation>Unique name of the SW implementing the task. Together with the SW_Version_Tag it identifies univocally the SW distribution containing the executable to be run</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="SW_Version_Tag" type="xs:string">
				<xs:annotation>
					<xs:documentation>Version of the SW distribution containing the task executable</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Executable" type="xs:string">
				<xs:annotation>
					<xs:documentation>Pathname of the Task executable. The pathname must be an absolute one, or relative to the root directory of the processor installation tree.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="CPU_Cores" type="Cores_Type">
				<xs:annotation>
					<xs:documentation>Specification of the required number of CPU cores.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="RAM" type="RAM_Type">
				<xs:annotation>
					<xs:documentation>Specification of the required amount of RAM.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="List_of_RAMDISKs" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Optional list of the required RAM-based volumes. If missing no such volume allocation is requested.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="RAMDISK" type="RAMDISK_Type_Scalable" minOccurs="0" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>Specification of the required RAM-based volumes.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="GPU" type="GPU_Type" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Optional element specifying the required GPU resources. If missing no
GPU resource is requested.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element ref="Disk_Space"/>
			<xs:element name="Timeout" type="xs:nonNegativeInteger">
				<xs:annotation>
					<xs:documentation>Maximum processing time in seconds allowed before aborting the request. Upon the timeout is expired, the PF shall send a signal, specified by the “Killing_Signal” parameter, to the running task to stop its execution. A value of “0” means that no timeout is applied.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Killing_Signal">
				<xs:annotation>
					<xs:documentation>Signal to be used by the processing facility to stop the execution of the Task executable. Possible values are in the range [1, 64].</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="1"/>
						<xs:maxInclusive value="64"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Critical">
				<xs:annotation>
					<xs:documentation>Task criticality flag. Possible values are:
•	“Yes”: a failure of this task shall abort the execution of the complete task table.
•	“No”: a failure of this task is not considered blocking and the execution of the other tasks shall continue nominally.
</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="YesNo_Type">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="List_of_Proc_Parameters">
				<xs:annotation>
					<xs:documentation>List of Proc_Parameter elements.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Proc_Parameter" type="TT_Proc_Parameter_Type" minOccurs="0" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>Parameter to be passed to the task executable via the Job Order.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="List_of_Cfg_Files">
				<xs:annotation>
					<xs:documentation>List of Cfg_File elements.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Cfg_File" type="Cfg_File_Type" minOccurs="0" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>Configuration file information.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="List_of_Inputs">
				<xs:annotation>
					<xs:documentation>List of Input elements.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Input" type="TT_Input_Type" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>Input data to be selected for processing.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="List_of_Outputs">
				<xs:annotation>
					<xs:documentation>List of Output elements.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Output" type="TT_Output_Type" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>Output data to be generated by the Task.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="List_of_Intermediate_Outputs">
				<xs:annotation>
					<xs:documentation>List of intermediate outputs supported by Task.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Intermediate_Output" type="TT_Intermediate_Output_Type" minOccurs="0" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>An intermediate output is usually generated for debugging purposes.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="List_of_Exit_Codes">
				<xs:annotation>
					<xs:documentation>List of Exit_Code elements containing the mapping of Task’s exit codes to their description.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Exit_Code" type="Exit_Code_Type" minOccurs="0" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>This optional element allows to map the exit code value to its descrip-tion.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<!--=====================================================================-->
</xs:schema>
