# Project: BIOMASS Processing Suite (BPS)
#
# Copyright (c) 2025, ARESYS S.r.l.
# Developed under contract with the European Space Agency (ESA)
#
# SPDX-License-Identifier: MIT

"""
XSD common annotation models L2
-------------------------------
"""

from bps.transcoder.io.common_annotation_models_l2.models import (
    AcquisitionListType,
    AcquisitionType,
    AgbIndexingType,
    AzimuthPolynomialType,
    BackscatterLimitsType,
    BpsFnfType,
    CalAbcoverageTilesListType,
    CalAbcoverageType,
    CalAbfilteredCoverageType,
    CalibrationScreenType,
    ChannelImbalanceList,
    ChannelType,
    Complex,
    ComplexArray,
    CrossTalkList,
    DatumType,
    DoubleArray,
    DoubleArrayWithUnits,
    DoubleWithUnit,
    FloatArray,
    FloatArrayWithUnits,
    FloatWithChannel,
    FloatWithPolarisation,
    FloatWithUnit,
    GeneralConfigurationParametersType,
    GeodeticReferenceFrameType,
    GncoverageListType,
    GncoverageTilesListType,
    GncoverageType,
    GnfilteredCoverageType,
    GroupType,
    HeightModelBaseType,
    HeightModelType,
    InputInformationL2AType,
    InputInformationL2BL3ListType,
    IntArray,
    IntegerListType,
    InterferometricPairListType,
    InterferometricPairType,
    LayerListType,
    LayerType,
    MinMaxNumType,
    MinMaxType,
    MinMaxTypeWithUnit,
    MissionPhaseIdtype,
    MissionType,
    NoDataValueChoiceType,
    OperationalModeType,
    OrbitPassType,
    PercentPixelsType,
    PixelRepresentationChoiceType,
    PixelRepresentationType,
    PixelTypeChoiceType,
    PixelTypeType,
    PolarisationListType,
    PolarisationType,
    ProductL2AType,
    ProductL2BL3Type,
    ProductType,
    ProjectionType,
    RasterImageType,
    SelectedReferenceImageType,
    SensorModeType,
    SlantRangePolynomialType,
    StaQualityParametersListType,
    StaQualityParametersType,
    StaQualityType,
    StateType,
    StringListType,
    SubsettingRuleType,
    SwathType,
    TimeTypeWithPolarisation,
    UnsignedIntWithGroup,
    UomType,
)
